apiVersion: 1

datasources:
  - name: ClickHouse (nlm_traces)
    uid: clickhouse_nlm_traces
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: nlm_traces
      defaultTable: otel_traces
      secure: false
      tlsSkipVerify: false
    isDefault: true
    editable: false
